import unitmath from "unitmath";

export type UnitFactory = ReturnType<typeof unitmath.config<number>>;
export type Unit = ReturnType<UnitFactory>;

export const unit: UnitFactory = unitmath.config({
	definitions: {
		units: {
			tbsp: {
				value: "15 ml",
				aliases: ["tbsp", "tbs", "tb", "tablespoon"],
			},
			tsp: {
				value: "1/3 tbsp",
				aliases: ["tsp", "ts", "t", "teaspoon"],
			},
			things: {
				value: "1",
				aliases: [
					"slice",
					"slices",
					"serving",
					"servings",
					"thing",
					// "things",
					"item",
					"items",
					"piece",
					"pieces",
					"portion",
					"portions",
					"part",
					"parts",
					"unit",
					"units",
					"chunk",
					"chunks",
					"hunk",
					"hunks",
					"slab",
					"slabs",
					"sliver",
					"slivers",
					"wedge",
					"wedges",
					"container",
					"containers",
					"package",
					"packages",
					"dash",
					"dashes",
					"stalk",
					"stalks",
				],
			},
			bit: {
				value: "1 thing",
				aliases: ["bit", "bits"],
			},
		},
		systems: {
			normal: [
				"m",
				"meter",
				"s",
				"A",
				"kg",
				"degC",
				"mol",
				"rad",
				"b",
				"F",
				"C",
				"S",
				"V",
				"J",
				"N",
				"Hz",
				"ohm",
				"H",
				"cd",
				"lm",
				"lx",
				"Wb",
				"T",
				"W",
				"Pa",
				"ohm",
				"sr",
			],
		},
	},
});
